### ISSUE TITLE
Container Service Kubernetes fixes

### ISSUE THREAD

**Issue by mrusyd** [Australian-Imaging-Service/charts#112]
- [ ] Kubernetes Job object recreated by the CS plugin mounts XNAT archive and build directories as the hostpath volume type, this makes the Job object tightly coupled with the underlying storage technology. As these 2 data volumes do need to be mounted on every worker node for job container to read and write, but if it requires manual mount, it makes node autoscaling impossible in K8s. Also, on cloud infrastructure, mounting of NAS volumes on worker node is often handled by cloud provider’s specific storage plugins, the mount points can change on worker node under some circumstances. For example, when XNAT also runs in Kubernetes and data volumes are mounted into XNAT container using Persistent Volume Claim volume type, when the XNAT pod is replaced with a new one, the volume mount points will change on worker nodes. When this happens, it breaks hostpath volumes used by XNAT job container. It would be good if the CS plugins abstracts away the underlying storage by using PVC instead of hostpath. 

- [ ] Scheduling the container job on worker node has limitation. XNAT admin can only specify which worker node to run container jobs at top level that applies to all container jobs. XNAT admins are not able to select which group of worker node to run which contain jobs. It would be good if the CS plugin can look into certain label attributes in the container image commands and use them in the Job object for selecting worker nodes. Also, allowing configuring project level labels may accommodate some use cases.

- [ ] Multiple label selectors for nodes are a bit too restrictive to use.

- [ ] The status of previously 100% completed jobs could change from “Complete” to “Failed” unexpectedly. It could be triggered under certain scenarios; one appears after changing of the CS plugin configuration.

**Comment by fxusyd** [comment]
- [ ] Kubernete Job object recreated by the CS plugin mounts XNAT archive and build directories as the hostpath volume type, this makes the Job object tightly coupled with the underlying storage technology. As these 2 data volumes do need to be mounted on every worker node for job container to read and write, but if it require manual mount, it makes node autoscaling impossible in K8s. Also, on cloud infrastructure, mounting of NAS volumes on worker node is often handled by cloud provider’s specific storage plugins, the mount points can change on worker node under some circumstances. For example, when XNAT also runs in Kubernetes and data volumes are mounted into XNAT container using Persistent Volume Claim volume type, when the XNAT pod is replaced with a new one, the volume mount points will change on worker nodes. When this happens, it breaks hostpath volumes used by XNAT job container. It would be good if the CS plugins abstracts away the underlying storage by using PVC instead of hostpath. 

- [ ] Scheduling the container job on worker node has limitation. XNAT admin can only specify which worker node to run container jobs at top  level that applies to all container jobs. XNAT admins are not able to select which group of worker node to run which contain jobs. It would be good if the CS plugin can look into certain label attributes in the container image commands and use them in the Job object for selecting worker nodes. Also, allowing configuring project level labels may accommodate some use cases.

- [ ] Multiple label selectors for nodes are a bit too restrictive to use.

- [ ] The status of previously 100% completed jobs could change from “Complete” to “Failed” unexpectedly. It could be triggered under certain scenarios, one appears after changing of the CS  plugin configuration.

**Comment by mrusyd** [comment]
@fxusyd , do you have any update to share? I will follow up with Flywheel

**Comment by fxusyd** [comment]
Hi Milan, I've emailed John Flavin at Flywheel last Tuesday. He is the developer of the plugin.
