### ISSUE TITLE
[STORY] Set heapsize for tomcat on xnat-web pod startup

### ISSUE THREAD

**Issue by fxusyd** [Australian-Imaging-Service/charts#88]
Description:
> By default, the XNAT pod's tomcat uses Xms=512m and Xmx=4g, this is hardcoded as part of the container image. To modify the this settings, rebuild of image is required every time when this setting needs to be changed . As an system administrator, I need to be able to use the standard AIS xnat image and overwrite the Tomcat heap size in the container at pod initiation.

Acceptance Criteria:
> When the container is starting up, it should show the specified heap size as below
> - Xms = specified value
> - Xmx = specified value

**Comment by andrewbrock-sahmri** [comment]
It's hardcoded in the sense that it has a default value, but it can be overridden at build-time - see [Australian-Imaging-Service/xnat-build/#9](https://github.com/Australian-Imaging-Service/xnat-build/pull/9)

If we migrated away from Packer and just used normal Dockerfiles for building then any additional CATALINA_OPTS could just be passed through via an environment variable at runtime rather than people having to build their own custom Docker images?

**Comment by fxusyd** [comment]
enhancement included in commit 483bf9b
